#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            ref class VisualState;
        }
    }
}
namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class StackPanel;
                ref class Image;
                ref class Button;
                ref class TextBlock;
            }
        }
    }
}

namespace App3
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::VisualState^ wideState;
        private: ::Windows::UI::Xaml::VisualState^ narrowState;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ MainStack;
        private: ::Windows::UI::Xaml::Controls::Image^ Image;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Controls;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Labels;
        private: ::Windows::UI::Xaml::Controls::StackPanel^ Buttons;
        private: ::Windows::UI::Xaml::Controls::Button^ Btnpick;
        private: ::Windows::UI::Xaml::Controls::Button^ Btnreset;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Textblock1;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Textblock2;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Textblock3;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Textblock4;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Textblock5;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ Textblock6;
    };
}

